POST http://localhost:4015/with-api/api/passenger/join
content-type:application/json

{
    "passenger_queue_count":1
}
###

POST http://localhost:4015/with-api/api/passenger/leave
content-type:application/json

{
    "passenger_queue_count":-1
}

###

POST http://localhost:4015/with-api/api/taxi/join
content-type:application/json

{
    "taxi_queue_count":1
}

###
POST http://localhost:4015/with-api/api/taxi/depart
content-type:application/json

{
    "taxi_queue_count":-1
}