POST https://taxi-queue-qgy0.onrender.com/with-api/api/passenger/join
content-type:application/json

{
    "passenger_queue_count":1
}
###

POST https://taxi-queue-qgy0.onrender.com/with-api/passenger/leave
content-type:application/json

{
    "passenger_queue_count":-1
}

###

POST https://taxi-queue-qgy0.onrender.com/with-api/api/taxi/join
content-type:application/json

{
    "taxi_queue_count":1
}

###
POST https://taxi-queue-qgy0.onrender.com/with-api/api/taxi/depart
content-type:application/json

{
    "taxi_queue_count":-1,
    "passenger_queue_count":-12
}